import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { listProspects, serializeProspectRow } from "@/lib/query-utils";
import { toCsv } from "@/lib/csv";
import type { ProspectsQuery } from "@/lib/types";

/**
 * CSV export (spec §23): prospects (current filtered view or all),
 * companies, campaigns, activities, and full JSON backup.
 */
export async function GET(req: NextRequest) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;

  const sp = req.nextUrl.searchParams;
  const type = sp.get("type") ?? "prospects";
  const stamp = new Date().toISOString().slice(0, 10);

  if (type === "backup") {
    const [prospects, companies, campaigns, activities, settings, views] = await Promise.all([
      db.prospect.findMany({
        include: { company: { select: { id: true, name: true } }, campaign: { select: { id: true, name: true } } },
      }),
      db.company.findMany(),
      db.campaign.findMany(),
      db.activity.findMany({ orderBy: { occurredAt: "asc" } }),
      db.setting.findMany(),
      db.savedView.findMany(),
    ]);
    const payload = {
      format: "outreach-os-backup",
      version: 1,
      exportedAt: new Date().toISOString(),
      counts: {
        prospects: prospects.length, companies: companies.length,
        campaigns: campaigns.length, activities: activities.length,
      },
      data: {
        prospects: prospects.map(serializeProspectRow),
        companies: companies.map((c) => ({ ...c, createdAt: c.createdAt.toISOString(), updatedAt: c.updatedAt.toISOString() })),
        campaigns: campaigns.map((c) => ({
          ...c,
          startDate: c.startDate?.toISOString() ?? null,
          endDate: c.endDate?.toISOString() ?? null,
          createdAt: c.createdAt.toISOString(),
          updatedAt: c.updatedAt.toISOString(),
        })),
        activities: activities.map((a) => ({
          ...a,
          occurredAt: a.occurredAt.toISOString(),
          createdAt: a.createdAt.toISOString(),
        })),
        settings: Object.fromEntries(settings.map((s) => [s.key, s.value])),
        savedViews: views.map((v) => ({
          name: v.name, entityType: v.entityType, filters: JSON.parse(v.filtersJson),
        })),
      },
    };
    return new Response(JSON.stringify(payload, null, 2), {
      headers: {
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="outreach-backup-${stamp}.json"`,
      },
    });
  }

  if (type === "companies") {
    const companies = await db.company.findMany({
      include: { _count: { select: { prospects: true } } },
      orderBy: { name: "asc" },
    });
    const csv = toCsv(
      ["Name", "Website", "LinkedIn", "Industry", "Location", "Size", "Source", "Status", "Prospects", "Notes", "Created"],
      companies.map((c) => [
        c.name, c.website, c.linkedinUrl, c.industry, c.location, c.companySize,
        c.source, c.status, c._count.prospects, c.notes, c.createdAt.toISOString().slice(0, 10),
      ]),
    );
    return csvResponse(csv, `companies-${stamp}.csv`);
  }

  if (type === "campaigns") {
    const campaigns = await db.campaign.findMany({ orderBy: { name: "asc" } });
    const csv = toCsv(
      ["Name", "Status", "Target audience", "Started", "Ended", "Description", "Notes", "Created"],
      campaigns.map((c) => [
        c.name, c.status, c.targetAudience,
        c.startDate?.toISOString().slice(0, 10) ?? "", c.endDate?.toISOString().slice(0, 10) ?? "",
        c.description, c.notes, c.createdAt.toISOString().slice(0, 10),
      ]),
    );
    return csvResponse(csv, `campaigns-${stamp}.csv`);
  }

  if (type === "activities") {
    const activities = await db.activity.findMany({
      orderBy: { occurredAt: "desc" },
      include: {
        prospect: { select: { firstName: true, lastName: true } },
        company: { select: { name: true } },
        campaign: { select: { name: true } },
      },
    });
    const csv = toCsv(
      ["Date", "Type", "Prospect", "Company", "Campaign", "Notes", "Message", "Auto"],
      activities.map((a) => [
        a.occurredAt.toISOString().slice(0, 10), a.activityType,
        a.prospect ? `${a.prospect.firstName} ${a.prospect.lastName ?? ""}`.trim() : "",
        a.company?.name ?? "", a.campaign?.name ?? "",
        a.notes ?? "", a.messageText ?? "", a.autoGenerated ? "yes" : "no",
      ]),
    );
    return csvResponse(csv, `activities-${stamp}.csv`);
  }

  // prospects (default): honors the same filters as the table view.
  const q: ProspectsQuery = {
    query: sp.get("query") ?? undefined,
    status: sp.get("status") ?? undefined,
    priority: sp.get("priority") ?? undefined,
    companyId: sp.get("companyId") ?? undefined,
    campaignId: sp.get("campaignId") ?? undefined,
    verification: sp.get("verification") ?? undefined,
    hasFollowUp: sp.get("hasFollowUp") ?? undefined,
    missing: sp.get("missing") ?? undefined,
    issue: sp.get("issue") ?? undefined,
    ids: sp.get("ids") ?? undefined,
    sort: sp.get("sort") ?? undefined,
    order: (sp.get("order") as "asc" | "desc") ?? undefined,
    pageSize: 10000,
    archived: sp.get("archived") === "true",
  };
  const { rows } = await listProspects({ ...q, page: 1 });

  const csv = toCsv(
    [
      "First name", "Last name", "Job title", "Company", "LinkedIn URL", "Email",
      "Location", "Source", "Campaign", "Status", "Priority", "Fit score",
      "Verification", "Date added", "Request sent", "Connected", "First message",
      "Last contact", "Next follow-up", "Follow-ups sent",
    ],
    rows.map((p) => [
      p.firstName, p.lastName, p.jobTitle, p.company?.name ?? "",
      p.linkedinUrl, p.email, p.location, p.source, p.campaign?.name ?? "",
      p.status, p.priority, p.fitScore,
      p.verificationStatus ?? "Unverified",
      p.dateAdded.toISOString().slice(0, 10),
      p.connectionRequestDate?.toISOString().slice(0, 10) ?? "",
      p.connectionAcceptedDate?.toISOString().slice(0, 10) ?? "",
      p.firstMessageDate?.toISOString().slice(0, 10) ?? "",
      p.lastContactDate?.toISOString().slice(0, 10) ?? "",
      p.nextFollowUpDate?.toISOString().slice(0, 10) ?? "",
      p.followUpCount,
    ]),
  );

  const name = sp.get("scope") === "all" ? "prospects-all" : "prospects";
  return csvResponse(csv, `${name}-${stamp}.csv`);
}

function csvResponse(csv: string, filename: string): Response {
  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
