// Deterministic status/activity automation (spec §25).
// Rules:
//  - Status changes write an auditable "Status Change" activity (autoGenerated).
//  - Key dates are only ever FILLED when empty — never silently overwritten.
//  - Logging contact activities updates lifecycle dates and advances status.
//  - Nothing unrelated is mutated. Everything runs inside the caller's
//    transaction so prospect + activity stay consistent.

import type { Prisma, Activity } from "@prisma/client";
import type { ActivityType, ProspectStatus } from "./constants";

type Tx = Prisma.TransactionClient;

interface ProspectRecord {
  id: string;
  firstName: string;
  lastName: string | null;
  status: string;
  companyId: string | null;
  campaignId: string | null;
  connectionRequestDate: Date | null;
  connectionAcceptedDate: Date | null;
  firstMessageDate: Date | null;
  lastContactDate: Date | null;
  nextFollowUpDate: Date | null;
  archivedAt: Date | null;
}

const PRE_OUTREACH: string[] = [
  "Researching",
  "Needs Verification",
  "Verified",
  "Ready",
];

function fullName(p: { firstName: string; lastName: string | null }): string {
  return `${p.firstName}${p.lastName ? " " + p.lastName : ""}`;
}

async function writeActivity(
  tx: Tx,
  prospect: ProspectRecord,
  activityType: ActivityType | string,
  occurredAt: Date,
  notes?: string,
  messageText?: string,
): Promise<Activity> {
  return tx.activity.create({
    data: {
      prospectId: prospect.id,
      companyId: prospect.companyId,
      campaignId: prospect.campaignId,
      activityType,
      occurredAt,
      notes: notes ?? null,
      messageText: messageText ?? null,
      autoGenerated: true,
    },
  });
}

// ---------------------------------------------------------------------------
// Status change automation (PATCH /prospects/:id, bulk status changes)
// ---------------------------------------------------------------------------

export async function applyStatusChange(
  tx: Tx,
  prospect: ProspectRecord,
  newStatus: ProspectStatus | string,
  occurredAt: Date = new Date(),
): Promise<{ statusChanged: boolean; sideEffects: string[] }> {
  const sideEffects: string[] = [];
  const oldStatus = prospect.status;
  if (oldStatus === newStatus) return { statusChanged: false, sideEffects };

  const data: Prisma.ProspectUpdateInput = { status: newStatus };

  // Fill lifecycle dates when empty (never overwrite).
  if (newStatus === "Request Sent" && !prospect.connectionRequestDate) {
    data.connectionRequestDate = occurredAt;
    sideEffects.push("connection request date recorded");
  }
  if (newStatus === "Connected" && !prospect.connectionAcceptedDate) {
    data.connectionAcceptedDate = occurredAt;
    sideEffects.push("connection accepted date recorded");
  }
  if (newStatus === "Messaged" && !prospect.firstMessageDate) {
    data.firstMessageDate = occurredAt;
    sideEffects.push("first message date recorded");
  }
  if (
    ["Messaged", "Replied", "Meeting", "Follow-Up"].includes(newStatus) &&
    !prospect.lastContactDate
  ) {
    data.lastContactDate = occurredAt;
    sideEffects.push("last contact date recorded");
  }
  if (newStatus === "Archived") {
    data.archivedAt = occurredAt;
  } else if (oldStatus === "Archived") {
    data.archivedAt = null;
  }

  await tx.prospect.update({ where: { id: prospect.id }, data });

  // Auditable trail for every status change.
  await writeActivity(
    tx,
    prospect,
    "Status Change",
    occurredAt,
    `${oldStatus} → ${newStatus}`,
  );

  // Type-specific automation events (only when date was just filled,
  // so re-setting the same status never duplicates history).
  if (newStatus === "Request Sent" && data.connectionRequestDate) {
    await writeActivity(
      tx,
      prospect,
      "Connection Request",
      occurredAt,
      `Logged automatically when status changed to Request Sent (${fullName(prospect)})`,
    );
  }
  if (newStatus === "Connected" && data.connectionAcceptedDate) {
    await writeActivity(
      tx,
      prospect,
      "Connection Accepted",
      occurredAt,
      "Logged automatically when status changed to Connected",
    );
  }
  if (newStatus === "Messaged" && data.firstMessageDate) {
    await writeActivity(
      tx,
      prospect,
      "Message Sent",
      occurredAt,
      "Logged automatically when status changed to Messaged",
    );
  }

  return { statusChanged: true, sideEffects };
}

// ---------------------------------------------------------------------------
// Activity side-effects (POST activities / follow-up completion)
// ---------------------------------------------------------------------------

export async function applyActivityEffects(
  tx: Tx,
  prospect: ProspectRecord,
  activityType: ActivityType | string,
  occurredAt: Date,
): Promise<Prisma.ProspectUpdateInput> {
  const data: Prisma.ProspectUpdateInput = {};
  const forward = (targets: string[]) =>
    !TERMINAL.includes(prospect.status) && targets.includes(prospect.status);

  const TERMINAL = ["Converted", "Not Interested", "No Response", "Archived"];

  switch (activityType) {
    case "Connection Request": {
      if (!prospect.connectionRequestDate) data.connectionRequestDate = occurredAt;
      if (forward(PRE_OUTREACH) || prospect.status === "Request Sent") {
        data.status = "Request Sent";
      }
      break;
    }
    case "Connection Accepted": {
      if (!prospect.connectionAcceptedDate) data.connectionAcceptedDate = occurredAt;
      if (!TERMINAL.includes(prospect.status)) data.status = "Connected";
      break;
    }
    case "Message Sent": {
      if (!prospect.firstMessageDate) data.firstMessageDate = occurredAt;
      data.lastContactDate = occurredAt;
      if (forward([...PRE_OUTREACH, "Request Sent", "Connected", "Messaged"])) {
        data.status = "Messaged";
      }
      break;
    }
    case "Follow-Up Sent": {
      data.followUpCount = { increment: 1 };
      data.lastContactDate = occurredAt;
      if (forward([...PRE_OUTREACH, "Request Sent", "Connected", "Messaged", "Follow-Up"])) {
        data.status = "Follow-Up";
      }
      break;
    }
    case "Reply Received": {
      data.lastContactDate = occurredAt;
      if (!TERMINAL.includes(prospect.status)) data.status = "Replied";
      break;
    }
    case "Meeting": {
      data.lastContactDate = occurredAt;
      if (prospect.status !== "Converted") data.status = "Meeting";
      break;
    }
    case "Email": {
      data.lastContactDate = occurredAt;
      break;
    }
    // Research / Verification / Note / Status Change / Other: no date effects.
    default:
      break;
  }

  if (Object.keys(data).length > 0) {
    await tx.prospect.update({ where: { id: prospect.id }, data });
  }
  return data;
}

// ---------------------------------------------------------------------------
// Follow-up queue actions (spec §16)
// ---------------------------------------------------------------------------

export interface FollowUpActionInput {
  action: "complete" | "reschedule" | "skip" | "completeAndReschedule";
  date?: Date; // for reschedule / completeAndReschedule
  notes?: string;
  occurredAt?: Date;
}

export async function applyFollowUpAction(
  tx: Tx,
  prospect: ProspectRecord,
  input: FollowUpActionInput,
): Promise<string[]> {
  const now = input.occurredAt ?? new Date();
  const effects: string[] = [];

  if (input.action === "reschedule") {
    if (!input.date) throw new Error("A new date is required to reschedule.");
    await tx.prospect.update({
      where: { id: prospect.id },
      data: { nextFollowUpDate: input.date },
    });
    effects.push("follow-up rescheduled");
    return effects;
  }

  if (input.action === "skip") {
    // Clear the date without logging a contact (respectful skip).
    await tx.prospect.update({
      where: { id: prospect.id },
      data: { nextFollowUpDate: null },
    });
    await tx.activity.create({
      data: {
        prospectId: prospect.id,
        companyId: prospect.companyId,
        campaignId: prospect.campaignId,
        activityType: "Note",
        occurredAt: now,
        notes: input.notes?.trim()
          ? `Follow-up skipped: ${input.notes.trim()}`
          : "Follow-up skipped.",
        autoGenerated: true,
      },
    });
    effects.push("follow-up skipped");
    return effects;
  }

  // complete / completeAndReschedule → log the follow-up contact
  await tx.activity.create({
    data: {
      prospectId: prospect.id,
      companyId: prospect.companyId,
      campaignId: prospect.campaignId,
      activityType: "Follow-Up Sent",
      occurredAt: now,
      notes: input.notes?.trim() || null,
      autoGenerated: false,
    },
  });

  const data: Prisma.ProspectUpdateInput = {
    followUpCount: { increment: 1 },
    lastContactDate: now,
    nextFollowUpDate:
      input.action === "completeAndReschedule" && input.date ? input.date : null,
  };
  if (!TERMINAL_LIST.includes(prospect.status)) data.status = "Follow-Up";
  await tx.prospect.update({ where: { id: prospect.id }, data });
  effects.push("follow-up logged");
  if (input.action === "completeAndReschedule" && input.date) {
    effects.push("next follow-up scheduled");
  }
  return effects;
}

const TERMINAL_LIST = ["Converted", "Not Interested", "No Response", "Archived"];

// ---------------------------------------------------------------------------
// Field-level verification (spec §18)
// ---------------------------------------------------------------------------

export async function applyVerification(
  tx: Tx,
  prospect: ProspectRecord,
  verified: Record<string, boolean>,
  notes?: string,
  occurredAt: Date = new Date(),
): Promise<Prisma.ProspectUpdateInput> {
  const previous: Record<string, boolean> = prospectHasVerifiedFields(prospect)
    ? {}
    : {};
  const merged = { ...previous, ...verified };
  const verifiedCount = Object.values(merged).filter(Boolean).length;
  const total = Object.keys(merged).length || 1;

  let status: string;
  if (verifiedCount === 0) status = "Unverified";
  else if (verifiedCount < total) status = "Partial";
  else status = "Verified";

  const data: Prisma.ProspectUpdateInput = {
    verifiedFields: JSON.stringify(merged),
    verificationStatus: status,
    verifiedAt: occurredAt,
  };
  if (notes !== undefined) data.verificationNotes = notes || null;

  await tx.prospect.update({ where: { id: prospect.id }, data });
  await tx.activity.create({
    data: {
      prospectId: prospect.id,
      companyId: prospect.companyId,
      campaignId: prospect.campaignId,
      activityType: "Verification",
      occurredAt,
      notes: `Verification updated (${verifiedCount}/${total} fields verified)${notes ? ` — ${notes}` : ""}`,
      autoGenerated: true,
    },
  });
  return data;
}

function prospectHasVerifiedFields(p: ProspectRecord): boolean {
  return (p as ProspectRecord & { verifiedFields?: string | null }).verifiedFields != null;
}
