// Shared DTO types for the API contracts. Client and server both import these.

import type {
  ActivityType,
  CampaignStatus,
  Priority,
  ProspectStatus,
  VerificationStatus,
} from "./constants";

// ---------------------------------------------------------------------------
// Prospects
// ---------------------------------------------------------------------------

export interface ProspectRow {
  id: string;
  firstName: string;
  lastName: string | null;
  jobTitle: string | null;
  companyId: string | null;
  companyName: string | null;
  linkedinUrl: string | null;
  email: string | null;
  location: string | null;
  source: string | null;
  campaignId: string | null;
  campaignName: string | null;
  status: ProspectStatus | string;
  priority: Priority | string;
  fitScore: number | null;
  verificationStatus: string | null;
  dateAdded: string;
  connectionRequestDate: string | null;
  connectionAcceptedDate: string | null;
  firstMessageDate: string | null;
  lastContactDate: string | null;
  nextFollowUpDate: string | null;
  followUpCount: number;
  archivedAt: string | null;
  updatedAt: string;
}

export interface ActivityItem {
  id: string;
  prospectId: string;
  prospectName: string | null;
  companyId: string | null;
  companyName: string | null;
  campaignId: string | null;
  campaignName: string | null;
  activityType: ActivityType | string;
  occurredAt: string;
  notes: string | null;
  messageText: string | null;
  autoGenerated: boolean;
  createdAt: string;
}

export interface ProspectDetail extends ProspectRow {
  researchNotes: string | null;
  outreachAngle: string | null;
  notes: string | null;
  tags: string | null;
  verifiedFields: string | null;
  verificationNotes: string | null;
  verifiedAt: string | null;
  company: CompanyRow | null;
  campaign: CampaignRow | null;
  activities: ActivityItem[];
}

export interface ProspectsQuery {
  query?: string;
  status?: string;
  priority?: string;
  companyId?: string;
  campaignId?: string;
  verification?: string;
  hasFollowUp?: string; // "overdue" | "today" | "week" | "none" | "any"
  tag?: string;
  missing?: string; // company | role | linkedin | email | campaign
  invalid?: string; // linkedin
  issue?: string; // DQ issue keys
  ids?: string; // explicit id list (comma separated)
  sort?: string;
  order?: "asc" | "desc";
  page?: number;
  pageSize?: number;
  archived?: boolean;
}

export interface Paginated<T> {
  data: T[];
  total: number;
  page: number;
  pageCount: number;
}

export interface BulkActionRequest {
  ids: string[];
  action:
    | "status"
    | "priority"
    | "campaign"
    | "archive"
    | "restore"
    | "delete"
    | "verification";
  value?: string;
}

// ---------------------------------------------------------------------------
// Companies
// ---------------------------------------------------------------------------

export interface CompanyRow {
  id: string;
  name: string;
  website: string | null;
  linkedinUrl: string | null;
  industry: string | null;
  location: string | null;
  companySize: string | null;
  source: string | null;
  status: string;
  notes: string | null;
  tags: string | null;
  prospectCount: number;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Campaigns
// ---------------------------------------------------------------------------

export interface CampaignStats {
  totalProspects: number;
  requestsSent: number;
  accepted: number;
  acceptanceRate: number | null;
  messagesSent: number;
  replies: number;
  replyRate: number | null;
  meetings: number;
  conversions: number;
}

export interface CampaignRow {
  id: string;
  name: string;
  description: string | null;
  targetAudience: string | null;
  status: string;
  startDate: string | null;
  endDate: string | null;
  notes: string | null;
  stats: CampaignStats;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

export interface DashboardToday {
  overdueFollowUps: number;
  dueToday: number;
  recentAcceptances: ActivityItem[];
  recentReplies: ActivityItem[];
  needsVerification: number;
  recentlyAddedProspects: ProspectRow[];
  researchQueue: number;
}

export interface DashboardData {
  today: DashboardToday;
  pipeline: { status: string; count: number }[];
  recentActivity: ActivityItem[];
  activityVolume: { date: string; count: number }[];
  performance: {
    requestsSent: number;
    acceptanceRate: number | null;
    messagesSent: number;
    replyRate: number | null;
    meetings: number;
    conversions: number;
  };
  totals: {
    prospects: number;
    companies: number;
    activeCampaigns: number;
    archivedProspects: number;
  };
}

// ---------------------------------------------------------------------------
// Follow-up queue
// ---------------------------------------------------------------------------

export interface FollowUpItem {
  prospect: ProspectRow;
  daysOverdue: number | null;
  section:
    | "overdue"
    | "today"
    | "tomorrow"
    | "week"
    | "upcoming"
    | "nodate";
}

// ---------------------------------------------------------------------------
// Data quality
// ---------------------------------------------------------------------------

export type IssueSeverity = "high" | "medium" | "low";

export interface DataQualityIssue {
  key: string; // stable key for fixes / dismissals
  type: string;
  severity: IssueSeverity;
  title: string;
  description: string;
  prospectIds?: string[];
  companyIds?: string[];
  prospectCount?: number;
  companyCount?: number;
  fixLabel: string; // primary repair action label
  fixHref?: string; // view + optional target param
  dismissed?: boolean;
}

export interface DataQualitySummary {
  issues: DataQualityIssue[];
  dismissedCount: number;
  checkedProspects: number;
  checkedCompanies: number;
  generatedAt: string;
}

// ---------------------------------------------------------------------------
// Analytics
// ---------------------------------------------------------------------------

export interface AnalyticsData {
  range: { from: string; to: string; label: string };
  totals: {
    prospects: number;
    byStatus: { status: string; count: number }[];
    byCampaign: { campaignId: string; name: string; count: number }[];
    byCompany: { companyId: string; name: string; count: number }[];
  };
  outreach: {
    requestsSent: number;
    accepted: number;
    acceptanceRate: number | null;
    messagesSent: number;
    replies: number;
    replyRate: number | null;
    followUpsSent: number;
    followUpResponseRate: number | null;
    meetings: number;
    conversions: number;
    conversionRate: number | null;
  };
  series: {
    activityByDay: { date: string; count: number }[];
    prospectsAddedByDay: { date: string; count: number }[];
  };
}

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

export interface SearchResults {
  prospects: ProspectRow[];
  companies: CompanyRow[];
  campaigns: CampaignRow[];
  activities: ActivityItem[];
  counts: { prospects: number; companies: number; campaigns: number; activities: number };
}

// ---------------------------------------------------------------------------
// CSV import
// ---------------------------------------------------------------------------

export interface ImportPreviewRow {
  index: number;
  values: Record<string, string>;
  duplicateLinkedin: boolean;
  duplicateEmail: boolean;
  errors: string[];
  matchedProspectId?: string;
}

export interface ImportPreview {
  headers: string[];
  rows: ImportPreviewRow[];
  mapping: Record<string, string>; // csv header -> field name
  availableFields: { field: string; label: string; required: boolean }[];
  validCount: number;
  duplicateCount: number;
  errorCount: number;
}

export interface ImportResult {
  created: number;
  updated: number;
  skipped: number;
  companiesCreated: number;
  errors: string[];
}

// ---------------------------------------------------------------------------
// Settings / session
// ---------------------------------------------------------------------------

export interface SessionInfo {
  authenticated: boolean;
  email?: string;
  name?: string;
}
