import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { serializeProspectRow } from "@/lib/query-utils";

/** Global search across prospects, companies, campaigns, activities (spec §24). */
export async function GET(req: NextRequest) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;

  const q = req.nextUrl.searchParams.get("q")?.trim() ?? "";
  if (q.length < 2) {
    return Response.json({
      prospects: [], companies: [], campaigns: [], activities: [],
      counts: { prospects: 0, companies: 0, campaigns: 0, activities: 0 },
    });
  }

  const [prospects, companies, campaigns, activities] = await Promise.all([
    db.prospect.findMany({
      where: {
        archivedAt: null,
        OR: [
          { firstName: { contains: q } },
          { lastName: { contains: q } },
          { jobTitle: { contains: q } },
          { email: { contains: q } },
          { company: { name: { contains: q } } },
        ],
      },
      include: { company: { select: { id: true, name: true } }, campaign: { select: { id: true, name: true } } },
      take: 6,
      orderBy: { updatedAt: "desc" },
    }),
    db.company.findMany({
      where: { OR: [{ name: { contains: q } }, { industry: { contains: q } }, { location: { contains: q } }] },
      include: { _count: { select: { prospects: true } } },
      take: 5,
      orderBy: { name: "asc" },
    }),
    db.campaign.findMany({
      where: { OR: [{ name: { contains: q } }, { description: { contains: q } }, { targetAudience: { contains: q } }] },
      take: 4,
      orderBy: { name: "asc" },
    }),
    db.activity.findMany({
      where: {
        OR: [{ notes: { contains: q } }, { messageText: { contains: q } }],
      },
      include: {
        prospect: { select: { firstName: true, lastName: true } },
        company: { select: { name: true } },
        campaign: { select: { name: true } },
      },
      orderBy: { occurredAt: "desc" },
      take: 6,
    }),
  ]);

  return Response.json({
    prospects: prospects.map(serializeProspectRow),
    companies: companies.map((c) => ({
      id: c.id,
      name: c.name,
      website: c.website,
      linkedinUrl: c.linkedinUrl,
      industry: c.industry,
      location: c.location,
      companySize: c.companySize,
      source: c.source,
      status: c.status,
      notes: c.notes,
      tags: c.tags,
      prospectCount: c._count.prospects,
      createdAt: c.createdAt.toISOString(),
      updatedAt: c.updatedAt.toISOString(),
    })),
    campaigns: campaigns.map((c) => ({
      id: c.id,
      name: c.name,
      description: c.description,
      targetAudience: c.targetAudience,
      status: c.status,
      startDate: c.startDate?.toISOString() ?? null,
      endDate: c.endDate?.toISOString() ?? null,
      notes: c.notes,
      createdAt: c.createdAt.toISOString(),
      updatedAt: c.updatedAt.toISOString(),
      stats: {
        totalProspects: 0, requestsSent: 0, accepted: 0, acceptanceRate: null,
        messagesSent: 0, replies: 0, replyRate: null, meetings: 0, conversions: 0,
      },
    })),
    activities: activities.map((a) => ({
      id: a.id,
      prospectId: a.prospectId,
      prospectName: a.prospect
        ? `${a.prospect.firstName}${a.prospect.lastName ? " " + a.prospect.lastName : ""}`
        : null,
      companyId: a.companyId,
      companyName: a.company?.name ?? null,
      campaignId: a.campaignId,
      campaignName: a.campaign?.name ?? null,
      activityType: a.activityType,
      occurredAt: a.occurredAt.toISOString(),
      notes: a.notes,
      messageText: a.messageText,
      autoGenerated: a.autoGenerated,
      createdAt: a.createdAt.toISOString(),
    })),
    counts: {
      prospects: prospects.length,
      companies: companies.length,
      campaigns: campaigns.length,
      activities: activities.length,
    },
  });
}
