import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { bulkActionSchema, zodErrorMessage } from "@/lib/validation";
import { applyStatusChange } from "@/lib/automation";
import { PROSPECT_STATUSES, PRIORITIES } from "@/lib/constants";

export async function POST(req: NextRequest) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Could not read the request." }, { status: 400 });
  }

  const parsed = bulkActionSchema.safeParse(body);
  if (!parsed.success) {
    return Response.json({ error: zodErrorMessage(parsed.error) }, { status: 400 });
  }
  const { ids, action, value } = parsed.data;

  // Validate values before touching anything.
  if (action === "status") {
    if (!value || !PROSPECT_STATUSES.includes(value as never)) {
      return Response.json({ error: `"${value}" is not a valid status.` }, { status: 400 });
    }
  }
  if (action === "priority") {
    if (!value || !PRIORITIES.includes(value as never)) {
      return Response.json({ error: `"${value}" is not a valid priority.` }, { status: 400 });
    }
  }
  if ((action === "campaign" || action === "verification") && value === undefined) {
    return Response.json({ error: "A target value is required for this action." }, { status: 400 });
  }

  const count = await db.prospect.count({ where: { id: { in: ids } } });
  if (count === 0) {
    return Response.json({ error: "None of the selected prospects exist anymore." }, { status: 404 });
  }

  try {
    const affected = await db.$transaction(async (tx) => {
      if (action === "delete") {
        await tx.prospect.deleteMany({ where: { id: { in: ids } } });
        return { deleted: count };
      }
      if (action === "archive") {
        const now = new Date();
        await tx.prospect.updateMany({
          where: { id: { in: ids } },
          data: { archivedAt: now, status: "Archived" },
        });
        // one auditable activity per prospect
        const rows = await tx.prospect.findMany({ where: { id: { in: ids } } });
        for (const p of rows) {
          await tx.activity.create({
            data: {
              prospectId: p.id,
              companyId: p.companyId,
              campaignId: p.campaignId,
              activityType: "Status Change",
              occurredAt: now,
              notes: `${p.status} → Archived (bulk action, ${rows.length} records)`,
              autoGenerated: true,
            },
          });
        }
        return { archived: rows.length };
      }
      if (action === "restore") {
        const rows = await tx.prospect.findMany({ where: { id: { in: ids } } });
        const now = new Date();
        for (const p of rows) {
          await tx.prospect.update({
            where: { id: p.id },
            data: { archivedAt: null, status: p.status === "Archived" ? "Researching" : p.status },
          });
          await tx.activity.create({
            data: {
              prospectId: p.id,
              companyId: p.companyId,
              campaignId: p.campaignId,
              activityType: "Status Change",
              occurredAt: now,
              notes: "Archived → Researching (restored)",
              autoGenerated: true,
            },
          });
        }
        return { restored: rows.length };
      }
      if (action === "status") {
        const rows = await tx.prospect.findMany({ where: { id: { in: ids } } });
        const now = new Date();
        for (const p of rows) {
          await applyStatusChange(tx, p, value!, now);
        }
        return { updated: rows.length };
      }
      if (action === "priority") {
        await tx.prospect.updateMany({
          where: { id: { in: ids } },
          data: { priority: value! },
        });
        return { updated: count };
      }
      if (action === "campaign") {
        await tx.prospect.updateMany({
          where: { id: { in: ids } },
          data: value ? { campaignId: value } : { campaignId: null },
        });
        return { updated: count };
      }
      // verification
      await tx.prospect.updateMany({
        where: { id: { in: ids } },
        data: { verificationStatus: value!, verifiedAt: new Date() },
      });
      return { updated: count };
    });

    return Response.json({ ok: true, ...affected, requested: ids.length, matched: count });
  } catch (e) {
    return Response.json(
      { error: "The bulk change failed and nothing was saved. Try again." },
      { status: 500 },
    );
  }
}
