"use client";

// Activity timeline used in the prospect drawer and company/campaign views.
// Compact, scannable: date rail on the left, type badge + context on the right.

import type { ActivityItem } from "@/lib/types";
import { format, isSameDay } from "date-fns";
import { ActivityTypeBadge } from "./status-badge";
import { cn } from "@/lib/utils";

export function Timeline({
  activities,
  emptyLabel = "No activity yet.",
  emptyHint,
  compact = false,
}: {
  activities: ActivityItem[];
  emptyLabel?: string;
  emptyHint?: string;
  compact?: boolean;
}) {
  if (activities.length === 0) {
    return (
      <div className="px-1 py-8 text-center">
        <p className="text-[13px] font-medium text-foreground">{emptyLabel}</p>
        {emptyHint ? (
          <p className="mt-1 text-[12.5px] text-muted-foreground">{emptyHint}</p>
        ) : null}
      </div>
    );
  }

  // Precompute day-group boundaries (no reassignment during render).
  const dayBreaks = new Set<string>();
  let lastDay = "";
  for (const a of activities) {
    const key = format(new Date(a.occurredAt), "yyyy-MM-dd");
    if (key !== lastDay) dayBreaks.add(a.id);
    lastDay = key;
  }

  return (
    <ol className="relative space-y-0">
      {activities.map((a) => {
        const showDay = dayBreaks.has(a.id);
        return (
          <li key={a.id} className="relative">
            {showDay ? (
              <div className="sticky top-0 z-10 -mx-1 mb-1 mt-3 bg-card px-1 py-1 first:mt-0">
                <p className="font-num text-[11px] font-semibold tracking-wide text-muted-foreground uppercase">
                  {format(new Date(a.occurredAt), "EEEE, MMM d, yyyy")}
                </p>
              </div>
            ) : null}
            <div
              className={cn(
                "flex items-start gap-3 border-l border-border py-1.5 pl-3",
                compact ? "min-h-0" : "min-h-[2.5rem]",
              )}
            >
              <div className="mt-1 min-w-0 flex-1 space-y-1">
                <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
                  <ActivityTypeBadge type={a.activityType} />
                  {a.autoGenerated ? (
                    <span
                      className="text-[10.5px] text-muted-foreground/70"
                      title="Recorded automatically by status automation"
                    >
                      auto
                    </span>
                  ) : null}
                  {a.campaignName ? (
                    <span className="text-[11px] text-muted-foreground">{a.campaignName}</span>
                  ) : null}
                </div>
                {a.notes ? (
                  <p className="whitespace-pre-wrap text-[13px] leading-relaxed text-foreground/90">
                    {a.notes}
                  </p>
                ) : null}
                {a.messageText ? (
                  <blockquote className="rounded-sm border-l-2 border-primary/40 bg-surface-subtle px-2.5 py-1.5 text-[12.5px] leading-relaxed text-foreground/80 italic">
                    {a.messageText}
                  </blockquote>
                ) : null}
              </div>
              <time
                dateTime={a.occurredAt}
                className="font-num mt-0.5 shrink-0 text-[11px] text-muted-foreground"
              >
                {format(new Date(a.occurredAt), isSameDay(new Date(), new Date(a.occurredAt)) ? "HH:mm" : "MMM d")}
              </time>
            </div>
          </li>
        );
      })}
    </ol>
  );
}
