import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { applyActivityEffects } from "@/lib/automation";
import { activityCreateSchema, zodErrorMessage } from "@/lib/validation";

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;
  const { id } = await params;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Could not read the request." }, { status: 400 });
  }

  const parsed = activityCreateSchema.safeParse({ ...((body as object) ?? {}), prospectId: id });
  if (!parsed.success) {
    return Response.json({ error: zodErrorMessage(parsed.error) }, { status: 400 });
  }
  const data = parsed.data;

  const prospect = await db.prospect.findUnique({ where: { id } });
  if (!prospect) {
    return Response.json({ error: "Prospect not found — the activity was not logged." }, { status: 404 });
  }

  const occurredAt = data.occurredAt ? new Date(data.occurredAt) : new Date();
  if (isNaN(occurredAt.getTime())) {
    return Response.json({ error: "The activity date is not a valid date." }, { status: 400 });
  }

  try {
    const activity = await db.$transaction(async (tx) => {
      const created = await tx.activity.create({
        data: {
          prospectId: prospect.id,
          companyId: data.companyId ?? prospect.companyId,
          campaignId: data.campaignId ?? prospect.campaignId,
          activityType: data.activityType,
          occurredAt,
          notes: data.notes,
          messageText: data.messageText,
          autoGenerated: false,
        },
      });
      // Deterministic side-effects (dates + status advance) — auditable.
      await applyActivityEffects(tx, prospect, data.activityType, occurredAt);
      return created;
    });

    return Response.json(
      {
        id: activity.id,
        activityType: activity.activityType,
        occurredAt: activity.occurredAt.toISOString(),
        sideEffectsApplied: true,
      },
      { status: 201 },
    );
  } catch (e) {
    return Response.json(
      { error: "Could not log the activity. Nothing was saved — try again." },
      { status: 500 },
    );
  }
}
