import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { mergeSchema, zodErrorMessage } from "@/lib/validation";

/**
 * Merge two prospect records (duplicate repair, spec §19).
 * Target keeps its identity; source's unique identifiers, notes, and
 * activities are moved over, then the source is deleted.
 */
export async function POST(req: NextRequest) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Could not read the request." }, { status: 400 });
  }
  const parsed = mergeSchema.safeParse(body);
  if (!parsed.success) {
    return Response.json({ error: zodErrorMessage(parsed.error) }, { status: 400 });
  }
  if (parsed.data.targetId === parsed.data.sourceId) {
    return Response.json({ error: "A record cannot be merged into itself." }, { status: 400 });
  }

  const { targetId, sourceId } = parsed.data;

  const result = await db.$transaction(async (tx) => {
    const target = await tx.prospect.findUnique({ where: { id: targetId } });
    const source = await tx.prospect.findUnique({ where: { id: sourceId } });
    if (!target || !source) throw new Error("One of the records no longer exists.");

    // Fill gaps on target (never overwrite existing values).
    await tx.prospect.update({
      where: { id: targetId },
      data: {
        linkedinUrl: target.linkedinUrl ?? source.linkedinUrl,
        email: target.email ?? source.email,
        jobTitle: target.jobTitle ?? source.jobTitle,
        companyId: target.companyId ?? source.companyId,
        campaignId: target.campaignId ?? source.campaignId,
        location: target.location ?? source.location,
        source: target.source ?? source.source,
        fitScore: target.fitScore ?? source.fitScore,
        notes: [target.notes, source.notes ? `(merged from ${source.firstName} ${source.lastName ?? ""}): ${source.notes}` : null]
          .filter(Boolean)
          .join("\n\n") || null,
      },
    });

    // Move activities to the target record.
    await tx.activity.updateMany({
      where: { prospectId: sourceId },
      data: { prospectId: targetId },
    });

    await tx.activity.create({
      data: {
        prospectId: targetId,
        companyId: target.companyId,
        campaignId: target.campaignId,
        activityType: "Note",
        occurredAt: new Date(),
        notes: `Merged duplicate record (${source.firstName} ${source.lastName ?? ""}).`,
        autoGenerated: true,
      },
    });

    await tx.prospect.delete({ where: { id: sourceId } });
    return tx.prospect.findUniqueOrThrow({
      where: { id: targetId },
      include: { company: { select: { id: true, name: true } }, campaign: { select: { id: true, name: true } } },
    });
  });

  return Response.json({ ok: true, mergedInto: targetId });
}
