import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { serializeProspectRow } from "@/lib/query-utils";
import { applyStatusChange } from "@/lib/automation";
import { prospectUpdateSchema, zodErrorMessage } from "@/lib/validation";
import { isValidEmail, isValidLinkedinUrl } from "@/lib/normalize";
import type { Prisma } from "@prisma/client";

type Params = { params: Promise<{ id: string }> };

function serializeActivity(a: {
  id: string; prospectId: string; companyId: string | null; campaignId: string | null;
  activityType: string; occurredAt: Date; notes: string | null; messageText: string | null;
  autoGenerated: boolean; createdAt: Date;
  prospect: { firstName: string; lastName: string | null } | null;
  company: { name: string } | null;
  campaign: { name: string } | null;
}) {
  return {
    id: a.id,
    prospectId: a.prospectId,
    prospectName: a.prospect ? `${a.prospect.firstName}${a.prospect.lastName ? " " + a.prospect.lastName : ""}` : null,
    companyId: a.companyId,
    companyName: a.company?.name ?? null,
    campaignId: a.campaignId,
    campaignName: a.campaign?.name ?? null,
    activityType: a.activityType,
    occurredAt: a.occurredAt.toISOString(),
    notes: a.notes,
    messageText: a.messageText,
    autoGenerated: a.autoGenerated,
    createdAt: a.createdAt.toISOString(),
  };
}

export async function GET(req: NextRequest, { params }: Params) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;
  const { id } = await params;

  const prospect = await db.prospect.findUnique({
    where: { id },
    include: {
      company: true,
      campaign: true,
      activities: {
        orderBy: { occurredAt: "desc" },
        take: 200,
        include: {
          prospect: { select: { firstName: true, lastName: true } },
          company: { select: { name: true } },
          campaign: { select: { name: true } },
        },
      },
    },
  });
  if (!prospect) {
    return Response.json({ error: "Prospect not found. It may have been deleted." }, { status: 404 });
  }

  const company = prospect.company;
  const campaign = prospect.campaign;
  return Response.json({
    ...serializeProspectRow(prospect),
    researchNotes: prospect.researchNotes,
    outreachAngle: prospect.outreachAngle,
    notes: prospect.notes,
    tags: prospect.tags,
    verifiedFields: prospect.verifiedFields,
    verificationNotes: prospect.verificationNotes,
    verifiedAt: prospect.verifiedAt?.toISOString() ?? null,
    company: company
      ? {
          id: company.id, name: company.name, website: company.website,
          linkedinUrl: company.linkedinUrl, industry: company.industry,
          location: company.location, companySize: company.companySize,
          source: company.source, status: company.status, notes: company.notes,
          tags: company.tags, prospectCount: 0,
          createdAt: company.createdAt.toISOString(), updatedAt: company.updatedAt.toISOString(),
        }
      : null,
    campaign: campaign
      ? {
          id: campaign.id, name: campaign.name, description: campaign.description,
          targetAudience: campaign.targetAudience, status: campaign.status,
          startDate: campaign.startDate?.toISOString() ?? null,
          endDate: campaign.endDate?.toISOString() ?? null, notes: campaign.notes,
          createdAt: campaign.createdAt.toISOString(), updatedAt: campaign.updatedAt.toISOString(),
          stats: {
            totalProspects: 0, requestsSent: 0, accepted: 0, acceptanceRate: null,
            messagesSent: 0, replies: 0, replyRate: null, meetings: 0, conversions: 0,
          },
        }
      : null,
    activities: prospect.activities.map(serializeActivity),
  });
}

export async function PATCH(req: NextRequest, { params }: Params) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;
  const { id } = await params;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Could not read the request." }, { status: 400 });
  }

  const parsed = prospectUpdateSchema.safeParse(body);
  if (!parsed.success) {
    return Response.json({ error: zodErrorMessage(parsed.error) }, { status: 400 });
  }
  const data = parsed.data;

  const existing = await db.prospect.findUnique({ where: { id } });
  if (!existing) {
    return Response.json({ error: "Prospect not found. Refresh the list and try again." }, { status: 404 });
  }

  // Duplicate identifier checks (exclude self).
  if (data.linkedinUrl && data.linkedinUrl !== existing.linkedinUrl) {
    const dupe = await db.prospect.findFirst({
      where: { linkedinUrl: data.linkedinUrl, id: { not: id } },
      select: { firstName: true, lastName: true },
    });
    if (dupe) {
      return Response.json(
        { error: `LinkedIn URL is already attached to ${dupe.firstName} ${dupe.lastName ?? ""}.` },
        { status: 409 },
      );
    }
  }
  if (data.email && data.email !== existing.email) {
    const dupe = await db.prospect.findFirst({
      where: { email: data.email, id: { not: id } },
      select: { firstName: true, lastName: true },
    });
    if (dupe) {
      return Response.json(
        { error: `Email is already attached to ${dupe.firstName} ${dupe.lastName ?? ""}.` },
        { status: 409 },
      );
    }
  }

  const toDate = (v: string | null): Date | null | undefined => {
    if (v === null) return null;
    if (v === undefined) return undefined;
    const d = new Date(v);
    if (isNaN(d.getTime())) {
      throw new Error(`"${v}" is not a valid date.`);
    }
    return d;
  };

  try {
    const updated = await db.$transaction(async (tx) => {
      const update: Prisma.ProspectUpdateInput = {};

      if (data.firstName !== undefined) update.firstName = data.firstName;
      if (data.lastName !== undefined) update.lastName = data.lastName;
      if (data.jobTitle !== undefined) update.jobTitle = data.jobTitle;
      if (data.linkedinUrl !== undefined) update.linkedinUrl = data.linkedinUrl;
      if (data.email !== undefined) update.email = data.email;
      if (data.location !== undefined) update.location = data.location;
      if (data.source !== undefined) update.source = data.source;
      if (data.priority !== undefined) update.priority = data.priority;
      if (data.fitScore !== undefined) update.fitScore = data.fitScore;
      if (data.researchNotes !== undefined) update.researchNotes = data.researchNotes;
      if (data.outreachAngle !== undefined) update.outreachAngle = data.outreachAngle;
      if (data.notes !== undefined) update.notes = data.notes;
      if (data.tags !== undefined) update.tags = data.tags;
      if (data.companyId !== undefined) update.company = data.companyId ? { connect: { id: data.companyId } } : { disconnect: true };
      if (data.campaignId !== undefined) update.campaign = data.campaignId ? { connect: { id: data.campaignId } } : { disconnect: true };
      if (data.nextFollowUpDate !== undefined) update.nextFollowUpDate = toDate(data.nextFollowUpDate);
      if (data.connectionRequestDate !== undefined) update.connectionRequestDate = toDate(data.connectionRequestDate);
      if (data.connectionAcceptedDate !== undefined) update.connectionAcceptedDate = toDate(data.connectionAcceptedDate);
      if (data.firstMessageDate !== undefined) update.firstMessageDate = toDate(data.firstMessageDate);

      let current = existing;
      if (Object.keys(update).length > 0) {
        current = await tx.prospect.update({ where: { id }, data: update });
      }

      if (data.status !== undefined && data.status !== existing.status) {
        const result = await applyStatusChange(tx, current, data.status);
        current = await tx.prospect.findUniqueOrThrow({ where: { id } });
        void result;
      }

      return tx.prospect.findUniqueOrThrow({
        where: { id },
        include: { company: { select: { id: true, name: true } }, campaign: { select: { id: true, name: true } } },
      });
    });

    return Response.json(serializeProspectRow(updated));
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    return Response.json(
      { error: `Could not save the prospect: ${message}` },
      { status: 400 },
    );
  }
}

export async function DELETE(req: NextRequest, { params }: Params) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;
  const { id } = await params;

  const existing = await db.prospect.findUnique({ where: { id }, select: { firstName: true, lastName: true } });
  if (!existing) {
    return Response.json({ error: "Prospect not found." }, { status: 404 });
  }

  await db.prospect.delete({ where: { id } });
  return Response.json({ ok: true });
}
