import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth";
import { activityCreateSchema, zodErrorMessage } from "@/lib/validation";
import { applyActivityEffects } from "@/lib/automation";

export async function GET(req: NextRequest) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;

  const sp = req.nextUrl.searchParams;
  const page = Math.max(1, Number(sp.get("page")) || 1);
  const pageSize = Math.min(200, Math.max(10, Number(sp.get("pageSize")) || 50));
  const type = sp.get("type");
  const prospectId = sp.get("prospectId");
  const campaignId = sp.get("campaignId");
  const companyId = sp.get("companyId");
  const from = sp.get("from");
  const to = sp.get("to");
  const query = sp.get("query")?.trim();

  const where: Record<string, unknown> = {};
  const and: Record<string, unknown>[] = [];
  if (type && type !== "all") and.push({ activityType: type });
  if (prospectId) and.push({ prospectId });
  if (campaignId) and.push({ campaignId });
  if (companyId) and.push({ companyId });
  if (from) and.push({ occurredAt: { gte: new Date(from) } });
  if (to) and.push({ occurredAt: { lte: new Date(to) } });
  if (query) {
    and.push({
      OR: [
        { notes: { contains: query } },
        { messageText: { contains: query } },
        { prospect: { OR: [{ firstName: { contains: query } }, { lastName: { contains: query } }] } },
      ],
    });
  }
  if (and.length) where.AND = and;

  const [total, activities] = await Promise.all([
    db.activity.count({ where }),
    db.activity.findMany({
      where,
      orderBy: { occurredAt: "desc" },
      skip: (page - 1) * pageSize,
      take: pageSize,
      include: {
        prospect: { select: { firstName: true, lastName: true } },
        company: { select: { name: true } },
        campaign: { select: { name: true } },
      },
    }),
  ]);

  return Response.json({
    data: activities.map((a) => ({
      id: a.id,
      prospectId: a.prospectId,
      prospectName: a.prospect
        ? `${a.prospect.firstName}${a.prospect.lastName ? " " + a.prospect.lastName : ""}`
        : null,
      companyId: a.companyId,
      companyName: a.company?.name ?? null,
      campaignId: a.campaignId,
      campaignName: a.campaign?.name ?? null,
      activityType: a.activityType,
      occurredAt: a.occurredAt.toISOString(),
      notes: a.notes,
      messageText: a.messageText,
      autoGenerated: a.autoGenerated,
      createdAt: a.createdAt.toISOString(),
    })),
    total,
    page,
    pageCount: Math.max(1, Math.ceil(total / pageSize)),
  });
}

export async function POST(req: NextRequest) {
  const guard = await requireSession(req);
  if ("response" in guard) return guard.response;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Could not read the request." }, { status: 400 });
  }
  const parsed = activityCreateSchema.safeParse(body);
  if (!parsed.success) {
    return Response.json({ error: zodErrorMessage(parsed.error) }, { status: 400 });
  }
  const data = parsed.data;

  const prospect = await db.prospect.findUnique({ where: { id: data.prospectId } });
  if (!prospect) {
    return Response.json(
      { error: "Pick a prospect before logging the activity — activities must attach to one." },
      { status: 400 },
    );
  }

  const occurredAt = data.occurredAt ? new Date(data.occurredAt) : new Date();
  if (isNaN(occurredAt.getTime())) {
    return Response.json({ error: "The activity date is not a valid date." }, { status: 400 });
  }

  try {
    const activity = await db.$transaction(async (tx) => {
      const created = await tx.activity.create({
        data: {
          prospectId: data.prospectId,
          companyId: data.companyId ?? prospect.companyId,
          campaignId: data.campaignId ?? prospect.campaignId,
          activityType: data.activityType,
          occurredAt,
          notes: data.notes,
          messageText: data.messageText,
          autoGenerated: false,
        },
      });
      await applyActivityEffects(tx, prospect, data.activityType, occurredAt);
      return created;
    });

    return Response.json({ id: activity.id }, { status: 201 });
  } catch (e) {
    return Response.json(
      { error: "Could not log the activity. Nothing was saved — try again." },
      { status: 500 },
    );
  }
}
